Add most populars
YurkinED/java-filmorate pull request #15
Opened 2022-11-06 18:03 UTC by Solntmore

<feat> Добавлена возможность выводить топ-N фильмов по количеству лайков.
<feat> Добавлены константы выполняющие поиск и сортировку по различным параметрам.
<refactor> Переработан контролер showMostLikedFilms, поддерживает GET /films/popular?count={limit}&genreId={genreId}&year={year}.

2022-11-06 20:13 UTC, YurkinED requested changes
В целом хорошо, но прийдется переделать

2022-11-06 20:13 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/constants/SqlQueryConstantsForFilm.java
> +    public static final String SQL_QUERY_FIND_FILM_BY_GENRE_YEAR_AND_SORT_BY_RATING = "SELECT f.film_id, f.film_name, " +
Ограничение на количество строк лучше ставить в самом запросе чтобы не засорять трафик и память лишними данными, например вот так:
SELECT * FROM FILMORATE.FILM 
order by FILM_ID desc
LIMIT 1
Необходимо переделать везде

2022-11-06 20:29 UTC, YurkinED requested changes

2022-11-06 20:29 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (genreId.isPresent() && year.isPresent()) {
А зачем разделять на 3 ветки если в итоге один и тот же метод вызывается. Давай 1 метод сделаем

2022-11-06 20:29 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/constants/SqlQueryConstantsForFilm.java
> +    public static final String SQL_QUERY_FIND_FILM_BY_GENRE_AND_SORT_BY_RATING = "SELECT f.film_id, f.film_name, " +
тут можно вот такое использовать условие чтобы совместить в случае если параметр не передан - то передавать -1. Но если сам переданный параметр <0, то выбрасывть исключение
 WHERE 
(fg.genre_id =:genre_id or  :genre_id=-1)
and (EXTRACT(YEAR FROM f.release_date)=:year  or   :year=-1)

а чтобы 2 раза не передавать параметр можно воспользоваться
join (select :genre_id as genre_id, :year as year) cr

Типа такого
SELECT * FROM FILMORATE.FILM 
join (select 1 as genre_idx, 1 as yearx) cr on 1=1
where 1=cr.genre_idx
order by FILM_ID desc
LIMIT 1

2022-11-06 20:29 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .limit(limit).collect(Collectors.toList());
тут огрничивать не потребуется, если  в запросе будет лимит

2022-11-06 20:29 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -    public List<Film> commonLikedFilms(int userId, int friendId) {
Почему эта часть удаляется, добавь плиз к себе чтобы не удалить ничего

2022-11-07 14:59 UTC, Solntmore commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        System.out.println(SQL_QUERY_FIND_FILM_FILTER);
Я так понимаю для проверки писал, можно удалять)

2022-11-07 15:02 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        System.out.println(SQL_QUERY_FIND_FILM_FILTER);
точно!

2022-11-07 15:06 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -    public List<Film> commonLikedFilms(int userId, int friendId) {
А выше добавляется - не критично

2022-11-07 15:08 UTC, YurkinED approved these changes

2022-11-07 16:11 UTC, MikhailKuznets approved these changes

2022-11-07 16:48 UTC, MikhailKuznets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                "с id жанра {} за {} год.",limit, genreId, year);
Возможно не хватает еще 2х параметров: 
limit, genreId, year, **_genreId, year_**

2022-11-07 16:50 UTC, Solntmore commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                "с id жанра {} за {} год.",limit, genreId, year);
Верно подмечено

2022-11-07 16:54 UTC, YurkinED commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                "с id жанра {} за {} год.",limit, genreId, year);
Спасибо

2022-11-07 16:55 UTC, merged